README.md, part.hpp
I've confirmed that OpenFPGALoader works fine with GOWIN GW1N-LV4LQ100 if I add its device code to `part.hpp`.
So please add GW1N-4 device code to support GW1N-4 devices.
=> Add GOWIN GW1N-4

.gitignore, CMakeLists.txt, README.md, src/altera.cpp, src/xilinx.cpp
This removes the hardcoded paths to allow configurability (useful for packaging).
With this patch, the paths are passed as macros added at compiler invocation; in particular, the macro `DATA_DIR` is, by default, `"/usr/local/share"`. This is done by taking advantage of the GNUInstallDirs feature of CMake to locate the `.../share` directory.
In this case, this should cleaner than a generated file.
=> make installation directory configurable

src/main.cpp
This includes the case when no argument is given, but `--list-boards`, etc. should still work.
=> Print error when no bitfile is specified

src/part.hpp
Added new part: xc7a100.
This works directly when using `--board=arty`.
=> Add support for Arty A7-100T

CMakeLists.txt, src/gowin.cpp, src/spiFlash.cpp
Initial Mac implementation that includes cmake modifications and clang compilation support.
For example, one of the following errors where fixed during implementation of Mac support:
```
Scanning dependencies of target openFPGALoader
[  4%] Building CXX object CMakeFiles/openFPGALoader.dir/src/spiFlash.cpp.o
/code/github/openFPGALoader/src/spiFlash.cpp:92:14: error: variable-sized object may not be initialized
uint8_t jtx[xfer_len] = {reverseByte(cmd)};
^~~~~~~~
/code/github/openFPGALoader/src/spiFlash.cpp:187:13: error: variable-sized object may not be initialized
uint8_t tx[len+3] = {(uint8_t)(0xff & (addr >> 16)),
^~~~~
```
=> Initial Mac OS X support

README.md, src/main.cpp
Hi,
this is another change I need for a project at work. This pull request adds a new option `--speed` / `-s`, which sets the JTAG frequency. It can deal with postfixes, so `-s 1M` or `-s 100k` both work fine.
A few miscellaneous thoughts:
- should the code responsible for parsing be moved to `parse_opt`?
- I didn't add range checks, is this taken care of down-range?
Thanks again, this tool is just so incredibly convenient when compared to Lattice's sluggish tools!
Martin
=> add jtag frequency option

CMakeLists.txt, README.md, src/altera.cpp, src/bitparser.cpp, src/dirtyJtag.cpp, src/ftdiJtagBitbang.cpp, src/ftdipp_mpsse.cpp, src/gowin.cpp, src/jtag.cpp, src/lattice.cpp, src/latticeBitParser.cpp, src/main.cpp
As discussed in #38 - the change to cxxopts instead of libargp plus some other minor changes enables us to pretty easily build this for Windows too!
=> cxxopts migration and windows (MinGW) support

README.md, src/cable.hpp, src/main.cpp
Some boards have FTDI JTAG connected to the FPGA on different channel.
It's helpful to be able to provide the channel on command line.
=> Add FTDI channel selection command line argument.

README.md, src/ftdiJtagBitbang.cpp, src/ftdiJtagBitbang.hpp, src/ftdiJtagMPSSE.cpp, src/ftdiJtagMPSSE.hpp, src/ftdipp_mpsse.cpp, src/ftdipp_mpsse.hpp, src/ftdispi.cpp, src/jtag.cpp, src/jtag.hpp, src/main.cpp
Hi again,
I needed a way to work with multiple FTDI devices attached to a single PC, so I added an option to specify the serial number (USB string descriptor) for selecting the right device.
There are a few other changes related to the way the JTAG device is constructed. Previously, there were two constructors for everything, with and without the `dev` parameter. Since, ultimately, there are no differences between calling the constructor with an empty string as the dev parameter or calling the other constructor without the dev parameter, I removed the constructors without the dev parameter, as to not add even more code overhead.
The one actually relevant change is in 73 of `src/ftdipp_mpsse.cpp`.
Let me know your thoughts!
Martin
=> add ftdi serial number argument

99-openfpgaloader.rules
This automatically grants the device to the currently logged in user,
without the need for a group.
Leave the old plugdev group for backwards compatibility.
=> Add uaccess tag to udev rules to work on distros without plugdev group

README.md, src/part.hpp
I tested this with my custom board (https://github.com/Disasm/honeycomb-pcb) and the `-b tangnano` openFPGALoader option. Both SRAM and flash programming work. Should I add a separate board definition for my board? I don't think I will be able to manufacture these boards in the nearest future.
=> Add support for GW1NS-2C FPGA chips

README.md, src/board.hpp, src/part.hpp
add support for kintex xc7k325t, found for example on the KC705 dev board.
While I've not tested it yet, I'm sure flashing the QSPI works as well. Only problem is that a licence in required to generate a bitstream for this device family. So it's probably a good idea to partition the makefile in devices that can be used with the free version, and then the others, or something similar.
=> add support for kintex xc7k325t

src/dirtyJtag.cpp
This is the changes that I mentioned. Right now the speed of dirtyJtag is limited by the USB traffic....
=> dirtyJtag optimizations to cut the number of USB requests

README.md, src/cable.hpp, src/cmsisDAP.cpp
Hi, [Orbtrace](https://github.com/orbcode/orbtrace) is an open source FPGA-based debug and trace interface with CMSIS-DAP support. Attached patches makes openFPGALoader work with it.
The second patch removes the product string check. CMSIS-DAP specification states that the string «CMSIS-DAP» can either be placed in the product string or the interface string for the actual interface, and since Orbtrace is a composite device with both CMSIS-DAP v1 (HID) and v2 (bulk) interfaces being optional features, presence is only being announced by each interface string.
Since hidapi doesn't expose interface strings, there's no easy way to check them, and since we're currently only calling `hid_enumerate()` with the VID/PID combination for the selected cable anyway, I propose just removing all string …
=> Add Orbtrace support

src/board.hpp, src/main.cpp
As some boards are known to run with higher TCK frequencies, allow a board-specific default to be specified in the board configuration table.
The only board affected by this change is the Digilent Arty which now defaults to 10MHz JTAG clock (which I tested), but the mechanism is generic and other boards can be modified as and when required.
The user can still override the frequency from the command line.
=> Add board specific default frequency

.github/workflows/Test.yml
This PR adds Ubuntu jobs to the CI workflow. As commented in #65, it'd be desirable to use a DEB recipe for generating the package, instead of just creating a tarball (which does not have metadata about the runtime dependencies). However, the tarball is useful, since it allows users to get binaries (as long as they install the deps themselves).
=> ci: add Ubuntu jobs

.github/workflows/Test.yml
Artifacts don't have a fixed URL and users need to login into GitHub in order to download them. Conversely, release assets do have a fixed URL and can be downloaded without login. Hence, this PR uses an action ([eine/tip](https://github.com/eine/tip)) for uploading the artifacts as assets of pre-release 'nightly'.
Note that it will only upload them if all jobs are successful, and only on branch 'master' or on tagged commits.
Actually, it works for tagged releases too. On untagged commits, the assets in 'nightly' will be updated. On tagged commits, a release will be created; it uses semver to decide whether it needs to be a release or a pre-release.
=> ci: use eine/tip to release artifacts

src/progressBar.cpp
The progress markers of the progress bar were output to stderr while the rest was output to stdout.
This patch moves everything to stdout.
=> progressBar: Use only stdout.

src/xilinx.cpp
Allowed frequency is up to 10 MHz according to xc95XXXxl_1532.bsd
=> xilinx: Adapt wait times with JTAG frequency.

CMakeLists.txt, src/feaparser.cpp, src/feaparser.hpp, src/jedParser.hpp, src/lattice.cpp, src/lattice.hpp, src/main.cpp
Added support for the MachXO3D, which has some significant differences to MachXO3LF. Not yet added support for security (public key signing / authentication of bitstream and encryption). Lattice generates the feature row and feabits in a separate file which is not in JED format. MachXO3D has dual boot and two CFG areas, specifying the CFG area program on the command line allows a file generated for CFG0/UFM0 to be programmed into CFG1/UFM1. There are also 4 UFM areas (UFM0, UFM1, UFM2 and UFM3).
=> adding support for MachXO3D

.github/workflows/Test.yml
Since this repo is public and open source, there is no need to limit the maximum number of parallel jobs. If more jobs are required, additional jobs will be queued and executed automatically. Nonetheless, the limit is 18-20 concurrent jobs, which is not frequent in this repo.
=> ci: rm 'max-parallel'

.github/workflows/Test.yml
In v2.6.0 of Action setup-msys2, option 'pacboy' was added. That allows to slightly cleanup the syntax used in the CI workflow.
=> ci/win: use option 'pacboy' of setup-msys2

.github/workflows/Test.yml
Close #140 
This PR is based on #140. Instead of declaring the list of MSYS2 jobs twice, it is declared once, and used in the matrices of jobs win-makepkg and make-test.
=> ci/win: add job 'win-jobs'

.github/workflows/Test.yml
When the Sphinx documentation was added, I overlooked that the whole site was being uploaded to the "nightly" release, uncompressed! I'm sorry about that 😭 
This PR fixes that issue. The documentation artifact is named, and it is compressed in a tarball, so that the release action can push it without file explosion.
=> ci/Release: replace openFPGALoader-Documentation subdir with a tarball

doc/compatibility/fpga.rst, src/part.hpp
Anlogic EF2M45 is a FPGA with a co-packaged 4Mbit SPI Flash, and the
JTAG interface is the same with EG4S20.
Add support for it by adding it to the part database.
SPI Flash programming and SRAM programming are both tested.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
=> part: add support for Anlogic ELF2 EF2M45

doc/compatibility/board.rst, doc/compatibility/fpga.rst, src/board.hpp, src/efinix.cpp, src/part.hpp
This is the support for Ti60 dev kit.
Please have a look before merging it.
This is the FTDI part of the dev board:
It works on my board:
=> efinix: add support for Titanium Ti60 f225 dev kit

src/main.cpp
This PR adds the missing object creation in for the `CologneChip` class in the new dynamic fashion for SPI targets.
I  tested the master branch on the GateMate programmer and evaluation board hardware and it is OK.
=> colognechip integration: create CologneChip SPI object in dynamic fashion as well

.github/workflows/Test.yml
It seems that some change in `tar` is producing issues when trying to extract `.zst` files in the CI workflow. This PR uses `zstd` explicitly, in order to work around it.
I reported the issue to MSYS2 maintainers, and they are having a look at the problem. Hence, this fix might not be needed in a few days. @trabucayre, it's up to you to merge this PR, or to just wait for it to be fixed upstream. The main motivation for this PR is making you aware.
=> ci: fix step 'Show package content'

.github/workflows/Test.yml
I contributed a composite action and a reusable workflow to msys2/setup-msys2, in order to reduce the duplication in all the repos building and testing MSYS2 packages. This PR replaces the `win` jobs in the CI workflow in order to use those. The functionality is the same.
Find references about the differences of Action and Workflow kinds in https://github.com/pyTooling/Actions/#context.
=> ci: use reusable composite action and reusable workflow from msys2/setup-msys2

doc/compatibility/fpga.rst
This PR fixes a missing space in a ref.
=> doc/compatibility/fpga: fix ref

.gitignore, doc/boards.py, doc/boards.yml, doc/compatibility/board.rst, doc/conf.py, doc/requirements.txt
Instead of manually writing the board compatibility table in the docs, this PR uses a YAML file and a Python script:
- Boards are declared in the YAML file, which provides a machine-readable solution for consumers of this repo to query the data.
- The Python script reads the YAML file and generates a restructuredtext table through [tabulate](https://pypi.org/project/tabulate/).
No content is changed, so the documentation looks exactly the same. This is an internal enhancement related to #105.
=> doc: declare board compatibility through a YAML file

doc/boards.py, doc/boards.yml, doc/conf.py
This is a follow-up of #160, related to #105.
An optional field, `Constraints`, is added to each item in `boards.yml`. `Constraints` can contain an string or a list of strings, matching the boad identifiers used in [hdl/constraints](https://github.com/hdl/constraints).
At the same time, an intersphinx mapping to hdl/constraints was added to the documentation configuration. When building the documentation, a new column is added to the boards compatibility table, which contains cross-references to [hdl.github.io/constraints/Data/Boards](https://hdl.github.io/constraints/Data/Boards). See [umarcor.github.io/openFPGALoader/compatibility/board](https://umarcor.github.io/openFPGALoader/compatibility/board).
@trabucayre, as discussed in …
=> doc: add field 'Constraints' to 'boards.yml'

.gitignore, doc/FPGAs.yml, doc/compatibility/fpga.rst, doc/conf.py, doc/data.py
As commented in https://github.com/trabucayre/openFPGALoader/issues/105#issuecomment-1012832344, this PR updates the documentation to declare the FPGA compatibility list through a YAML file (as done with the boards already).
=> doc: declare FPGA compatibility list through YAML file

doc/FPGAs.yml, doc/boards.yml, src/board.hpp, src/fsparser.cpp, src/part.hpp
The chip used by Sipeed Tang Nano 9K, GW1NR-LV9QN88PC6/I5, belongs to GW1NR-9C family.
Add support for it.
=> Add support for Gowin GW1NR-9C

doc/FPGAs.yml, doc/boards.yml, src/board.hpp, src/part.hpp
Adds support for the [GW1NZ-1](https://www.gowinsemi.com/en/product/detail/46/) chip and the new [Tang Nano 1K](https://www.aliexpress.com/item/1005002551785169.html?spm=a2g0o.store_pc_groupList.8148356.2.78981d42dwD89o) board.
I'm not entirely sure about what's the purpose of the `Memory` and `Flash` fields in the `boards.yml` file (copy-pasted from `tangnano4k`) so they might not be set correctly.
=> board: add tangnano1k

src/ice40.hpp
The following compiler warnings are resolved by adding appropriate override specifiers:
In file included from openFPGALoader/src/ice40.cpp:6:
openFPGALoader/src/ice40.hpp:26:8: warning: 'dumpFlash' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
bool dumpFlash(uint32_t base_addr, uint32_t len);
^
openFPGALoader/src/device.hpp:46:16: note: overridden virtual function is here
virtual bool dumpFlash(uint32_t base_addr, uint32_t len) {
^
In file included from openFPGALoader/src/ice40.cpp:6:
openFPGALoader/src/ice40.hpp:34:7: warning: 'spi_put' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
int spi_put(uint8_t cmd, uint8_t *tx, uint8_t *rx,
^
openFPGALoader/src/spiInterface.hpp:65:14: note: overridden …
=> ice40: Add override specifier to resolve compiler warnings

src/part.hpp
This pull request enable to program bitstream in sram for a QMTech Cyclone V Core Board 5CEFA5F23. 
I will try to add support for writing bitstream in flash in another pull request.
=> Add Cyclone V 5CEFA5 in part database

CMakeLists.txt
* Making the indentation even across the whole file
* Use dynamic linking on macOS and fix its pkg-config usage in the process. This should render openFPGALoader agnostic to the location of Homebrew's prefix, and solve compatibility issues with MacPorts. It also removes all the dirty Make hacks which were necessary for macOS.
=> CMakeLists: fix general code styling, use dynamic linking on macOS

doc/guide/install.rst
This PR adds instructions explaining how to install openFPGALoader on macOS from sources, using packages from Homebrew.
=> doc/guide: Add instructions for manual installation on macOS

doc/FPGAs.yml, src/part.hpp
Hi!
This PR adds support for the xc7k410t variant of the kintex 7. This is the fpga part used in the USRP X310. I've tested flashing the SRAM on this device using the integrated Digilent JTAG cable. I've also tested the existing xc7k325t support with a USRP X300 and verified flashing the SRAM works as well.
Please let me know if y'all have any feedback. Thanks for such a cool project!
=> part: Add kintex7 variant xc7k410t

doc/boards.yml, doc/vendors/colognechip.rst, src/colognechip.cpp, src/colognechip.hpp
This pull request ensures compatibility with the final evaluation board version. More info, datasheet and schematics are available [here](https://colognechip.com/programmable-logic/gatemate-evaluation-board/).
Short overview:
* CFG_FAILED signal is no longer inverted
* minor fix in CFG_MD settings in `doc/vendors/colognechip.rst`
* update evaluation board URLs in `doc/boards.yml`
Thanks!
=> gatemate: fix failed signal polarity and update documentation

doc/boards.yml, src/board.hpp, src/part.hpp
This works as expected for a bare-bones "hello world" bitstream (tying LEDs to switches) on my ZCU106 board.
=> Add initial support for ZCU106 development board

src/part.hpp
This resulted in an error with GCC 12:
```
In file included from src/main.cpp:29:
src/part.hpp:148:1: error: narrowing conversion of ‘2165379139’ from ‘unsigned int’ to ‘int’ [-Wnarrowing]
148 | };
| ^
```
=> fix(part.hpp): use uint32_t instead of int for fpga_list index

src/altera.cpp, src/altera.hpp, src/main.cpp, src/spiInterface.cpp, src/spiInterface.hpp
Ref #221
Just a first quick approach (implemented only for Altera). Do you think this is the right direction?
Beside the added cmd line args a significant change is moving prepare_flash_access().
Other possbile ways I can see would be to add different ops to prog_type_t.
=> Add skip sram cmd

src/cmsisDAP.cpp
My user has permissions for the USB device but not for the hidraw device. This won't work, of course, but it shouldn't crash either.
Old behaviour:
```
$ ./openFPGALoader -c cmsisdap /dev/null
Found 1 compatible device:
0x0d28 0x0204 DAPLink CMSIS-DAP
Segmentation fault (core dumped)
```
New behaviour:
```
$ ./openFPGALoader -c cmsisdap /dev/null
Found 1 compatible device:
0x0d28 0x0204 DAPLink CMSIS-DAP
JTAG init failed with: Couldn't open device. Check permissions for /dev/hidraw2
```
Additional information:
```
$ ls -l /dev/hidraw2
crw------- 1 root root 245, 2 Jul  2 16:21 /dev/hidraw2
$ lsusb|grep 0204
Bus 003 Device 021: ID 0d28:0204 NXP ARM mbed
$ ls -l /dev/bus/usb/003/021
crw-rw-r-- 1 root dialout 189, 276 Jul  2 16:21 /dev/bus/usb/003/021
```
I haven't applied …
=> cmsisDAP: fix crash in case hid device cannot be opened

src/jtag.cpp
before:
```
$ ./openFPGALoader -c cmsisdap /dev/null
Jtag: unknown cable type
JTAG init failed with: std::exception
```
after:
```
$ ./openFPGALoader -c cmsisdap /dev/null
Jtag: support for cmsisdap was not enabled at compile time
JTAG init failed with: std::exception
```
It took me a while to realize that the error was not due to a typo or misunderstanding. NixOS is building it without hidapi so support for cmsisdap is automatically disabled.
=> cmsisDAP: better error message if support is not enabled

doc/cable.yml, src/cable.hpp
Open Source Hardware JTAG/SWD/UART/SWO interface board based on FTDI FT2232H
https://github.com/diegoherranz/steppenprobe
Config taken from OpenOCD repo:
https://sourceforge.net/p/openocd/code/ci/master/tree/tcl/interface/ftdi/steppenprobe.cfg
Many thanks for this project!
=> Add Steppenprobe cable

doc/FPGAs.yml, src/part.hpp
Tested loading bitstream with Trenz KCU035 SoM. After adding IDCODE it worked like a charm :)
=> Add Xilinx Kintex UltraScale KCU035 IDCode

src/spiFlash.cpp, src/spiFlashdb.hpp
Reading of very large binaries (e.g. 32 MB) can cause stack overflow.
Put a reasonable limit on read burst length.
=> Limit automatic read burst length to 64K

CMakeLists.txt, scripts/msys2/PKGBUILD, src/altera.cpp, src/pathHelper.cpp, src/pathHelper.hpp, src/xilinx.cpp
Fixes #262 
Following the example from msys2 (https://www.msys2.org/wiki/Porting/) "Hard-coded paths and relocation"
> Sometimes these paths are baked into shell scripts or pkg-config's .pc files. In that case, you should use sed in the PKGBUILD package() function to correct this back to the msys2 version of the path. 
The package step can strip the `D:/a/msys64/` or equivalent prefix that's added at compile time.
```
-- Version installed from msys2 packages
$ strings /mingw64/bin/openFPGALoader.exe | grep mingw64/share
D:/a/msys64/mingw64/share/openFPGALoader/spiOverJtag_
-- Version installed from this PRs CI build
$ strings /c/Users/greg/Downloads/openFPGALoader | grep mingw64/share
/mingw64/share/openFPGALoader/spiOverJtag_
```
=> msys2: Fix windows paths

src/altera.hpp, src/anlogic.hpp, src/colognechip.hpp, src/device.hpp, src/efinix.hpp, src/gowin.hpp, src/ice40.cpp, src/ice40.hpp, src/lattice.hpp, src/main.cpp, src/spiFlash.cpp, src/spiInterface.cpp, src/spiInterface.hpp, src/xilinx.hpp
Adds a --bulk-erase command line option for bulk erasure of SPI flash.
Sometimes I want to completely erase the SPI flash, to stop the FPGA loading the contents and reverting to internal SRAM configuration.
This branch is NOT ready for merging yet - there are errors reported after the bulk erase occurs.
I'm submitting this as a question - is this something that should be added to openFPGALoader, and is it worth my effort to debug the errors, or does this have no hope of ever being accepted, hence I'd just keep it as a local branch and live with the errors (since they happen after the erase is done).
=> spiFlash: Add --bulk-erase command line option

doc/boards.yml, src/board.hpp
I'd like to report success in programming an ALINX AX516 Spartan-6 FPGA Development Board.
Programming just worked out of the box!  Thanks!
./openFPGALoader -v -v -c ft232 someproj.bit
gives the following output:
```
found 1 devices
index 0:
idcode 0x4002093
manufacturer xilinx
family spartan6
model  xc6slx16
irlength 6
File type : bit
```
I am programming it with an ALINX AL321 USB cable.  (Since external, I did not specify ft232 it in `board.hpp`, is that correct?)
Writing to flash also works (now with `-b alinx_ax516`), and tells:
```
Detected: Winbond W25Q128 256 sectors size: 128Mb
```
=> ALINX AX516 board.

doc/FPGAs.yml, doc/boards.yml, src/board.hpp, src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
Hey,
Here's a basic support for the Xilinx VCU118 board / Virtex UltraScale+ XCVU9P FPGA.
I could test it locally with a complex design and it works as expected.
The `spiOverJtag` image is missing.
I'll try to add it later in a new PR when I have access to a machine with Vivado and the proper (paid) license.
=> Add initial support for the Xilinx VCU118 board

doc/boards.yml, src/board.hpp
Sitlinv STLV7325 is a board with XC7K325T-FFG676.
Add support for it.
The board does not have JTAG cables on board, however its vendor provides an option to buy a FT4232-based JTAG cable with the board, so the default cable is set to ft4232.
Signed-off-by: Icenowy Zheng <uwu@icenowy.me>
=> boards: add Sitlinv STLV7325

src/bitparser.cpp
It was present before, but for some reason was removed in 16932786.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> bitparser: check bitstream length in the file

src/spiFlash.cpp
=> Add support for 4-byte QSPI flash addressing

doc/cable.yml
libgpiod is no longer actively developed on GitHub (the repo is archived). Active development happens on git.kernel.org instead.
=> doc/cable: Update libgpiod link

src/part.hpp
I found wrong information on the web when looking up the part name from the ID code.
Sorry about that.
=> Fix typo in part name and family.

doc/boards.yml, src/board.hpp, src/part.hpp, src/xilinx.cpp
Add bitstream loading to SRAM support for VCU128 board. Most parts are the same as VCU118 except for ftdi chip and IDCODE.
=> Add initial support for VCU128

src/main.cpp, src/xilinx.cpp, src/xilinx.hpp
Hi,
I extended the command line arguments "skip_load_bridge" and "skip_reset"  for Altera devices to be used with Xilinx devices.
Please let me know if there are some modifications necessary.
hycrypt
=> add the skip_load_bridge and skip_reset arguments for Xilinx devices

src/jlink.cpp, src/jlink.hpp, src/jtag.cpp
Add VID:PID override ability for JLink probes. Makes possible to use original Segger JLink PLUS probe which reports VID 0x1366  and PID 0x0101. 
Checked and worked fine programming GOWIN G1WN fpga chip.
=> Allow VID:PID override for JLink probe

src/lattice.cpp
Self-explanatory by the comment. I've personally confirmed this fixes at least the 1200HC parts.
=> Fix off-by-one errors in calculating UFM start page.

doc/cable.yml, doc/vendors/efinix.rst, src/cable.hpp, src/efinix.cpp, src/jlink.cpp, src/jlink.hpp
This adds:
* support for more SEGGER devices: J-Link BASE and J-Trace PRO
* JLINK fix when a bug observed when sending bitstreams to Efinix devices
* Efinix fix so JTAG works - tested with J-Link BASE as follows:
% ./openFPGALoader --cable jlink_base --index-chain 0 -m  ./path/to/design.bit
=> JLINK updates and Efinix JTAG fix

src/ftdipp_mpsse.cpp
Idea is to give user some more hints when open failed.
=> Tell USB bus and address when ftdi open fails.

src/main.cpp
Do not accept auto-detected base 0 (e.g. prefix '0x' for hex), since '0' prefix gives an octal interpretation, and the user is likely to copy values from `--scan-usb` or `lsusb` that could then be misinterpreted, e.g. 005:010.
See description in #354.
=> Parse USB bus:dev as decimal integers, to be consistent with `--scan-usb`.

src/part.hpp
This PR reorder a bit FPGA vendors/families to ease future additions and adds XCKU3P ID-Code.
=> ID-Codes cleanup and add XCKU3P ID-Code.

src/board.hpp, src/part.hpp
Adding the Avnet Mini-ITX dev board that uses the XC7Z100 Zynq-7000 device.
=> part/board: adding Avnet Mini-ITX

doc/FPGAs.yml, src/part.hpp
This is the device ID specifically for the FPGA we have on our board. The full part number of our FPGA is `XCKU115-2FLVB2104E`
=> Adding xcku115 to parts list

doc/boards.yml, src/board.hpp
I'd like to report success in programming an ALINX AX7102 Artix-7 FPGA Development Board.
Programming just worked out of the box! Thanks!
./openFPGALoader -v -v -c ft232 someproj.bit
gives the following output:
```
found 1 devices
index 0:
idcode 0x3631093
manufacturer xilinx
family artix a7 100t
model  xc7a100
irlength 6
```
I am programming it with an ALINX AL321 USB cable. 
Since it is external, I did not specify ft232 it in board.hpp.
However ALINX seems to ship one such cable with each board, so perhaps would make sense to specify it as a default cable?
Writing to flash also works (now with -b alinx_ax7102), and tells:
Detected: micron N25Q128_3V 256 sectors size: 128Mb
=> ALINX AX7102 board.

doc/boards.yml, src/board.hpp
Uses same FPGA-board as on the carrier AX7102, so essentially same as #397.
=> ALINX AX7101 board.

src/lattice.cpp
For NEXUS family fpgas, the Bscan register is 362 bits long or 45.25 bytes => 46 bytes.
This error was already corrected in `program_mem` (to program the sram).
In our case, we were interested in programming the external SPI Flash memory.
Tests have been carried out successfully on Certus-NX Versa, Crosslink-NX Evalualtion, CertusPro-NX Versa and GR740mini.
On CertusPro-NX Evaluation board instead, results were mixed: if the spi flash was not already programmed, then things were going fine. Otherwise, openFPGALoader doesn't manage to read/talk to the SPI Flash memory. We've already had issues with such board when programming the spi flash, so it may be that the sample we have in office is not working well.
=> Fix lattice bscan nexus in clearSRAM()

doc/FPGAs.yml, spiOverJtag/Makefile, spiOverJtag/build.py, spiOverJtag/xilinx_spiOverJtag.tcl, src/part.hpp
I just got this very affordable Kintex 70T board:
https://www.aliexpress.com/item/1005005572549665.html
I did not try spi over JTAG yet.
the default cmake / make / make install did not build it.
I also saw there were some entries missing for the 160t for consistency.
Let me know, what you think.
=> Add xc7k70t and small fixes for xc7k160t

src/jtag.cpp, src/jtag.hpp, src/main.cpp
This allows a user with other arbitrary devices on the bus to pass it on the command line rather than require parts.hpp to be aware of all jtag devices.  Eg, if a bus has multiple devices on the chain:
```
./openFPGALoader \
--cable jlink_base \
--detect
device type: J-Link major: 10 minor: 10 revision: 0
JTAG init failed with: Unknown device with IDCODE: 0x00c0ffee (manufacturer: 0x001 (), part: 0x10 vers: 0x0
./openFPGALoader \
--cable jlink_base \
--detect \
--misc-device "0xc0ffee,14,Coffee Maker"
device type: J-Link major: 10 minor: 10 revision: 0
index 0:
idcode 0x31820dd
manufacturer altera
family MAX 10
model  10M08SAU169C8G
irlength 10
index 1:
idcode   0x00c0ffee
type     Coffee Maker
irlength 14
```
=> Add user device list for non-fpga JTAG devices

src/colognechip.cpp, src/jtag.hpp
When used in a JTAG chain with multiple devices - and due to the additional bypass cycles - the 8-bit words in the DR register are not always contiguous. This PR sends the corresponding sequence of zeros so that there are always correct multiples of 8.
This allows configuration of individual GateMate FPGAs in a chain (using --index-chain).
=> gatemate: fix configuration byte alignment in jtag chains

src/part.hpp
I found this when I was trying to program a LCMXO2-4000HC, but openFPGALoader said it is a LCMX03LF-4300C:
$ openFPGALoader --detect
No cable or board specified: using direct ft2232 interface
Jtag frequency : requested 6.00MHz   -> real 6.00MHz
index 0:
idcode 0x12bc043
manufacturer lattice
family MachXO3LF
model  LCMX03LF-4300C
irlength 8
From what I found on the internet, the idcode for LCMX03LF-4300C seems to be 0x612BC043:
https://bsdl.info/details.htm?sid=b483da5dec63d6cd88ca59b002289d77
=> part: 0x012bc043 is for LCMXO2-4000HC

src/spiFlashdb.hpp
Digilent changed from Micron N25Q032A to Macronix MX25L3233F in 2020/2021, so this flash is needed in openfpgaloader to load to Cmod A7-35T
=> Update spiFlashdb.hpp for Macronix MX25L3233F used on Cmod A7-35T

src/xvc_client.cpp
In trying out openFPGALoader with a new (and therefore buggy) XVC server I managed to put openFPGALoader into a tight loop printing `Send instruction failed` when that server crashed.
Somewhat crudely, this PR `throw`s a c++ exception in the places where `ll_write()` errors were being ignored.  These exceptions are not caught, and so `abort()`.  An improvement, although not ideal.  It isn't clear to me how to communicate failure back through `Xilinx::program()`.
Also, add `sendall()` logic as TCP socket `send()` may enqueue some, but not all, of the requested bytes.
=> SVC client fixup error handling

src/xilinx.cpp
Needed for xc7s50 on VMM3 boards to detect FLASH.
=> xilinx.cpp: After programming, go to bypass, PR for #436

src/colognechip.cpp
Refers to issue #443.
JTAG and SPI routines are implemented primarily for FTDI-based configuration and flashing. This commit avoids using the FTDI-GPIOs for monitoring and controlling the `CFG_DONE`,  `CFG_FAILED`, reset and output-enable signals and allows SRAM configuration via JTAG using `dirtyJtag` cables.
=> gatemate: fix unintended gpio access with dirtyJtag cables

src/colognechip.cpp
Refers to an issue mentioned in #443.
With this set of commits, external flash can be configured with `dirtyJtag` via the built-in JTAG-SPI-bypass. There are also a few clean-ups, such as no duplicate calls of flash routines.
Tested with `-b gatemate_evb_{spi,jtag}`, `-b olimex_gatemateevb` and `-c dirtyJtag`.
=> gatemate: fix jtag-spi-bypass with dirtyJtag

src/spiFlash.cpp, src/spiFlashdb.hpp
This device was missing in spiFlashdb and is installed on the GateMate evaluation board.
MX25R6435F's status register contains a quad-enable bit.
If it is set, `SPIFlash::bp_to_len` incorrectly masks all sectors, even if no bp-bit is set. This fix seems obvious to me, but I don't have many boards to test this.
=> spiFlashdb: add MX25R6435F and fix SPIFlash::bp_to_len

doc/FPGAs.yml, spiOverJtag/Makefile, spiOverJtag/build.py, src/board.hpp, src/part.hpp
I could not test flash, because I am not sure of how to build a bistream for it.
I tried `./build.py ep4cgx15027`, but it errors.
when I cd into the tmp directory of it and run make manually I get the following error:
```
...
Error (12006): Node instance "altclkctrl_component" instantiates undefined entity "altclkctrl_inst". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP. File: /opt/intelFPGA_lite/22.1/quartus/libraries/megafunctions/alt_sfl_enhanced.v Line: 200
...
```
When I try to build the bistream for EP4CE15 I get the same error,
so I am not sure if that error is my fault.
Loading a bitstream into memory works.
=> Add EP4CGX150

doc/boards.yml, src/board.hpp, src/part.hpp
This Pull request adds support for AMD Virtex 7 FPGA VC709 Connectivity Kit.
=> Adding support for Xilinx Virtex 7 FPGA VC709 Connectivity Kit Board

src/part.hpp
Add IDCODE for Efinix Titanium Ti180.  SRAM loading seems to work fine, no bitstream available for SoJ yet.
=> part.hpp: add Efinix Titanium Ti180

src/part.hpp
Added ID for XC2C64A QFN48 chip.
=> Add xc2c64a QFN48

src/part.hpp
Key Changes:
Added support files for the Altera Max II EPM240T100C5N board.
Confirmed compatibility with SVF (Serial Vector Format) files for programming.
Usage:
openFPGALoader -c usb-blaster -m max2.svf
=> Add Support for Altera Max II EPM240T100C5N Board

doc/FPGAs.yml, doc/vendors/intel.rst
Add documentation for Max II and Cyclone II boards
- Included details on tested device models: EP2C5T144C8N and EPM240T100C5N
=> Update Max II and Cyclone II documentation

doc/guide/install.rst
Open fpga loader is [available](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/fpga.scm?h=master#n609), operational and up to date in the guix standard repositories. The advantage about other package managers is that users don't need to bother about dependencies, as they get installed along with it.
=> doc/guide/install.rst: instructions to install under Guix

doc/vendors/gowin.rst, src/gowin.cpp, src/gowin.hpp, src/main.cpp
Hi,
Gowin FPGA with built-in flash memory offer a separate "user flash" zone ([documentation](https://cdn.gowinsemi.com.cn/UG295E.pdf)), either accessible from programmable logic, or used as system memory for the EMCU. This memory can be configured by JTAG, but this isn't documented at the moment. We've reversed how flashing was performed for the GW1N9 FPGAs by sniffing the JTAG wires: it works in the same way you flash the bitstream, but with a different base address.
This PR implements user flash programming for GW1N(R)9 FPGAs (other models probably have different base addresses). The documentation lists this addition as experimental because of the reverse engineered nature of this development. A few safeguards have been implemented to prevent misuse of this functionality (FPGA model …
=> gowin: Implement User Flash programming for GW1N9

doc/guide/install.rst
openFPGALoader binary is available in Debian/Ubuntu repositories. Added installation instructions for these distributions. New Linux users may be confused by necessity to compile the program, added installation instructions for binary packages.
=> Debian/Ubuntu instructions for binary installation. Update install.rst

CMakeLists.txt
👋 seeing the [version mismatch doing the release build for 0.13.0](https://github.com/Homebrew/homebrew-core/pull/202864), bumping the version to match with the release. Thanks!
cc @trabucayre
=> fix: update version to patch with the release

.github/workflows/Test.yml
👋 [ubuntu 24 has been around for quite some time](https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/), adding it to the CI matrix.
=> ci: add ubuntu 24

src/part.hpp
Description:
STEP-MAX10 development board is equipped with Altera 10M02SCM153C8G. It is not in the support list. This PR adds this chip support. I have tested this change with my STEP-MAX10 development board. It runs as expected result. If this PR needs more inforamtion, please let me know, thanks.
Change:
Added 'Altera 10M02SCM153C8G' in fpga_list.
=> Add Altera 10M02SCM153C8G Support.

doc/FPGAs.yml, doc/boards.yml, src/board.hpp
Description:
STEP-MAX10 V1 board has the chip of Altera 10M02SCM153C8G as the following images. This PR adds this board support. The official website is here: https://wiki.stepfpga.com/step-max10
Changes:
1. doc/FPGAs.yml:
- added 10M02 in 'Max 10' section
3. doc/boards.yml:
- added step-max10_v1 information
5. src/board.hpp:
- added step-max10_v1 board support
=> Add STEP-MAX10 V1 board support.

doc/boards.yml, src/board.hpp
Description:
STEP-MXO2 V2 has the chip of Lattice LCMXO2-4000HC-4MG132CC and it also includes the FT232 chip for updating both RAM and FLASH. This PR adds this board support. The official website is at: https://wiki.stepfpga.com/xo2-4000hc
Changes:
1. doc/boards.yml
- added step-mxo2_v2 board information.
2. src/board.hpp
- added step-mxo2_v2 board support.
=> Add STEP-MXO2 V2 Board Support.

doc/FPGAs.yml
```Model: 10M02, 10M08``` 
is not correct yaml structure and parsing it generated `10m02,_10m08` (single) model instead of `10m02` and `10m08` models
=> doc/FPGAs.yml: Fix yml structure in Intel Max 10

src/dfuFileParser.cpp, src/fsparser.cpp, src/ftdipp_mpsse.cpp, src/latticeBitParser.cpp
Some code used snprintf on std::string objects.
This caused unexpected behaviour where '\0' was printed to the output file. 
This pull request adds intermediate char* buffer which is later used to initialize std::string.
This string is later resized to the correct expected length.
=> Fix snprintf usage

src/board.hpp
Added `alinx_ax7203` and `alinx_ax7201` boards to be able to be programmed with openFPGALoader. I had a problem with programming the board with [LiteX](https://github.com/enjoy-digital/litex) so I added the option to program the boards with `openFPGALoader` and tested it out with `./alinx_ax7203.py --load` and `./alinx_ax7201.py --load` commands.
The boards use an external JTAG programmer that has the FT232 chip.  Both the boards have the same FPGA chip which is 
`xc7a200tfbg484` with speed grade 2.
The pull request is being made because of the use of the aforementioned boards in the [wireguard-fpga](https://github.com/chili-chips-ba/wireguard-fpga) and [uberClock](https://github.com/chili-chips-ba/uberClock) project that use those boards.
=> Added alinx_ax7203 and alinx_ax7201 boards

src/gowin.cpp
`gowin.cpp` uses the functions `htole32()` and `le32toh()` without including the prerequisite header `<endian.h>`.  This breaks the build when using the musl libc.
=> gowin: Fix compilation on musl

src/libgpiodJtagBitbang.cpp, src/libgpiodJtagBitbang.hpp, src/xvc_server.cpp
Adds the method `writeTMSTDI()` to the libgpiod bitbang driver, making it usable for the XVC server mode.
I have only tested the APIV2 code, but the other one should work for symmetry reasons.  :smile_cat:
=> libgpiodJtagBitbang: add support for XVC server

src/xvc_server.cpp
If a thread throws an exception, the application will `abort()` through the `terminate()` function, preventing cleanup code from being run.
Without this fix, "pressing" to quit XVC server mode looks like this:
```
Press to quit
Read error (-1) 9 Bad file descriptor
connection closed - fd 8
terminate called after throwing an instance of 'std::runtime_error'
what():  communication failure
zsh: IOT instruction  ./openFPGALoader --xvc
```
The application exits on a signal, and no cleanup is done.  With the fix, we get this instead:
```
Press to quit
Read error (-1) 9 Bad file descriptor
connection closed - fd 8
thread exiting with error: communication failure
Xilinx Virtual Cable Stopped! 
```
I also added the missing call to `join()`, which should make the `_is_stopped` spin redundant, but I …
=> xvc_server: Make thread exit cleanly

src/spiFlashdb.hpp
Adding support for MX25L25645G SPI FLASH to set quad mode bit. Tested on hardware.
=> Added support for MX25L25645G FLASH memory

doc/boards.yml, doc/guide/advanced.rst, src/board.hpp, src/main.cpp, src/xilinx.cpp
Hi Trabucayre,
This PR enable the detection and the dump of the secondary QSPI.
Tested on KCU105:
=> kcu105: add support for secondary QSPI

src/svf_jtag.cpp
It looks like the LFE5U-85F fails to execute this SVF fragment:
! Shift in ISC ERASE(0x0E) instruction
SIR	8	TDI  (0E);
SDR	8	TDI  (01);
RUNTEST	IDLE	2 TCK	20.00E-03 SEC;
! Program Fuse Map
! Shift in LSC_READ_STATUS(0x3C) instruction
SIR	8	TDI  (3C);
SDR	32	TDI  (00000000)
TDO  (00000000)
MASK (0000B000);
The problem is with this:
RUNTEST	IDLE	2 TCK	20.00E-03 SEC;
If the jtag device isn't flushed before the host sleeps, the 2 clocks arrive just before the SIR and the FPGA sets a busy bit that fails the TDO check. In a way the sleep gets ahead of the 2 TCK. 
One can argue that the flush is really necessary only when min_duration is greater than 0  but it is hard to test so I prefer being conservative.
=> Fix incompatibility with Lattice FPGA

CMakeLists.txt
Just a suggestion. I was surprised when my debug build was not debug...
=> make ENABLE_OPTIM non effective for Debug builds configuration

99-openfpgaloader.rules, CMakeLists.txt, src/board.hpp, src/cable.hpp, src/esp_usb_jtag.cpp, src/esp_usb_jtag.hpp, src/jtag.cpp
see #501 
cc: @emard @edanuff
Ref: https://github.com/emard/esp32s3-jtag
Note: may requires a documentation page to explain howto prepare an ESP32.
=> Esp usb jtag Cable support

src/board.hpp, src/cable.hpp
Programming SRAM over USB works, when board jumpers are set for JTAG programming mode.
SPI flashing does not work properly (does not boot).
Readback of SPI data yields identical bitstream.
These changes are only tested with hardware revision 2 of the board.
This commit adds:
* a new cable `numato-neso`.
* a new board `neso_a7`.
Usage (programming):
`openFPGALoader -b neso_a7 top.bit`
Usage (flashing):
`openFPGALoader -b neso_a7 -f top.bit`
Detecting flash works:
```
openFPGALoader -b neso_a7 -f --detect
empty
write to flash
Jtag frequency : requested 30.00MHz   -> real 30.00MHz  
protect_flash: use: openFPGALoader/spiOverJtag//spiOverJtag_xc7a100tcsg324.bit.gz
load program
Load SRAM: [==================================================] 100.00%
Done
Shift IR 35
ir: 1 isc_done 1 isc_ena 0 …
```
=> Add support for Numatolab Neso board.

src/board.hpp
Programming to SRAM works. Programming flash works with a renamed spiOverJtag bitfile - cs(g)484 is different from fg(g)484, but the configuration flash IOs all end up on the same pads in the end.
(As an aside: I suspect that more Xilinx bitstreams are being generated than are actually needed. There's no physical difference between the silicon for e.g. xc6slx45csg324, xc6slx45fgg484, and xc6slx45csg484 - the configuration flash is connected to the same pads on each part, the pins are just named differently. As such, the same bitstream can be used for any package containing that part.)
=> Add support for Digilent Anvyl, the Big Red Board.

doc/boards.yml, src/board.hpp
This Pull request adds support for Open Source SDR Lab Kintex-7 325t FPGA PCIE Development Board
=> Adding support for Open Source SDR Lab Kintex-7 325t FPGA Board

doc/FPGAs.yml, doc/boards.yml, src/anlogicCable.cpp, src/board.hpp, src/part.hpp
1. Fix ANLOGICCABLE_VIDv1 to correct old value.
2. Add support for Anlogic EG4D20EG176 FPGA.
3. Add support for MLK-S200-EG4D20 board.
4. Update related document and outdated URL.
```
-> % ./openFPGALoader -b mlk-s200-eg4d20 --detect
empty
Jtag frequency : requested 6000000Hz -> real 6000000Hz
index 0:
idcode 0x4014c35
manufacturer anlogic
family eagle d20
model  EG4D20EG176
irlength 8
-> % ./openFPGALoader -b mlk-s200-eg4d20 mlk_s200_eg4d20.bit
empty
Jtag frequency : requested 6000000Hz -> real 6000000Hz
Parse file header end
DONE
Loading: [===================================================] 100.00%
Done
-> % ./openFPGALoader -b mlk-s200-eg4d20 -f mlk_s200_eg4d20.bit
empty
write to flash
Jtag frequency : requested 6000000Hz -> real 6000000Hz
Parse file header end
DONE
JEDEC ID: 0xef4015 …
```
=> Fix the failure of old Anlogic Cable and add support for Anlogic EG4D20EG176

doc/boards.yml, src/board.hpp
Hello!
I've made my own fpga board called [icepi zero](https://github.com/cheyao/icepi-zero). This might be offered as a prize in a hackathon @ Github hq (Check out [undercity](https://highway.hackclub.com/getting-started/undercity)!! I'm part of the organizing team), so I would like to add it to the supported boards list beforehand :D
Thanks.
=> Add support for icepi zero

src/cable.hpp
Fixes #562. The existing code suffices to use the new device as a JTAG programmer.
This assumption has been tested by forcing the VID:PID pair using `--vid 0x15ba --pid 0x002a`, but the PR itself remains untested until I have access to the device (this Thursday).
=> Add cable support for ARM-USB-TINY-H based off ARM-USB-OCD-H

doc/guide/install.rst
Udev rules are [included](https://codeberg.org/guix/guix/commit/690ac4fc2d) in openfpgaloader guix package.
This pr aims at documenting its use.
=> Document use of udev rules under GuixSystem
