trabucayre/openFPGALoader

README.md
=> adding support for kit and FPGA

README.md
Not tested but I think it was wrong.
=> fix gowin configuration command in readme

epcq.cpp, ftdipp_mpsse.cpp, ftdispi.cpp
As said in [this issue,](https://github.com/trabucayre/openFPGALoader/issues/11) some messages remain in french
=> english error message debug

board.hpp, part.hpp
For the moment, tangnano doesn't works:
```
$ openFPGALoader -v -m -b tangnano ./lcd_pjt/impl/pnr/lcd_pjt.fs
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
found 5 devices
Error: currently only one device is supported
```
=> Adding TangNano (gowin)

src/main.cpp
=> tab or space indentation, please choose

src/lattice.cpp
yeah, this should be pretty self-evident
https://github.com/trabucayre/openFPGALoader/blob/7b048d2d823ae70fd153bea44593e92c19bf275e/src/part.hpp#L35
=> fix MACHXO3LF family

INSTALL.md
=> More install instructions

src/anlogic.cpp, src/anlogicBitParser.cpp, src/board.hpp, src/cable.hpp, src/epcq.cpp, src/fsparser.cpp, src/ftdipp_mpsse.cpp, src/ftdispi.cpp, src/jedParser.cpp, src/lattice.cpp
Hello! 
I noticed that there were quite a few warnings produced during debug compilations and they feel legitimate to me. I fixed them, so we don't have to worry about them. 
Thanks!
=> Fix gcc 10.2 error messages.

README.md
=> TEC0117 can be flashed in memory and flash

src/part.hpp
With this change I can upload *.svf file,
it starts and works
=> recognize altera cyclone V 5CEBA4 FPGA

INSTALL.md
Hi,
This PR adds a small modification to the documentation, so that we don't need to replace YourUserName manually.
=> doc: retrieve username from $USER

src/ftdiJtagMPSSE.cpp
MPSSE can only do 8 * 0x10000 togles in one call. E.g. XC95 algorithmes do more toggles in one call. Break up these calls.
=> ftdiJtagMPSSE: Fix TCK toggle for large  numbers.

src/lattice.cpp, src/latticeBitParser.cpp
Added programming function to program, verify the public key for bitstream authentication - also enables authentication
=> Add bitstream authentication for MachXO3D

CMakeLists.txt
Current version number is stuck at 0.5.0... Fixes #142
=> Fix version number in CMakeLists.txt

doc/boards.yml, src/board.hpp
Adding two Xilinx development kit AC701 (artix7) and ZC702 (zynq)
=> Adding two Xilinx development kit AC701 (artix7) and ZC702 (zynq)

src/main.cpp
=> Nicer layout for the boards/fpga/cables table

doc/FPGAs.yml, doc/boards.yml, src/board.hpp, src/part.hpp
This pull request should be attributed to @sedwards-lab (see issue #159)
=> Add support  for Terasic DE1-SoC board

doc/boards.yml, src/board.hpp
This pull request adds support for Digilent [Zybo Z7](https://reference.digilentinc.com/reference/programmable-logic/zybo-z7/start) for SRAM writing only.
=> Add digilent_zybo_z7 10/20 support

.github/workflows/Test.yml
This PR adds macOS builds in CI.
=> Add CI for macOS

doc/guide/install.rst
* add missing backslash
* use sudo like all other commands
* might as well use apt for nice progress meter and stuff
=> Fix debian command

doc/FPGAs.yml, src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
=> Support for a couple of new Xilinx parts

src/spiFlash.cpp, src/spiFlashdb.hpp
Programming is slow, only one byte at a time :-(
See https://github.com/trabucayre/openFPGALoader/pull/203
=> Support for the Microchip SST25VF040B flash

src/efinix.cpp
Tested with Trion T120 BGA324 Development Kit but should work on all T20BGA324, T20BGA400, T35, T55, T85, and T120. This makes it possible to use generic FTDI JTAG cables which do not have the extra reset, oe and cs pins connected.
=> efinix: support loading a bitstream to SRAM using only JTAG pins (no GPIO)

doc/FPGAs.yml, src/part.hpp
This fixed issue #219 for me.
Was able to upload a working blinky.
=> support Kintex XC7K420T

src/board.hpp
Not sure if this matters at all, but it looks like I made a copy-paste error in #226 - this is the correct part for that board.
=> Correct part number for ZCU106 board

doc/FPGAs.yml, src/gowin.cpp, src/gowin.hpp, src/part.hpp
Checksum implementation is TODO.
=> Add GW2A support

doc/boards.yml, spiOverJtag/Makefile, spiOverJtag/build.py, spiOverJtag/constr_xc7s_csga225.xdc, spiOverJtag/xilinx_spiOverJtag.tcl, src/board.hpp
Tested on the CMOD s7 hardware and works.
=> Add support for xc7s_csga225 and the Digilent CMOD S7 board.

doc/boards.yml, src/board.hpp
Tested on Alchitry Au+ and works well on macOS Monterey
=> Update boards.yml - added Alchitry Au+

src/svf_jtag.cpp
I want to be able to parse and execute Lattice SVF files produced by Diamond. This still isn't a complete support for all SVF specifications but it is a step forward.
=> improve svf parsing.

src/altera.cpp, src/altera.hpp, src/anlogic.cpp, src/anlogic.hpp, src/main.cpp, src/svf_jtag.cpp
… in main.cpp
Fixed a type error in svf_jtag.cpp
=> Removed the svf programming code from devices and added device independent svf programming

src/spiFlashdb.hpp
=> Add support for MT25QU01 flash

doc/boards.yml, src/board.hpp, src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
=> Add support for XCVU9P IR length and codes

README.md, doc/boards.yml, src/main.cpp, src/spiInterface.hpp, src/xilinx.cpp, src/xilinx.hpp
Refer to #293.
~Depends on #297, so mark as draft for now.~ #297 is now merged, so opening for review.
=> Add target-flash and secondary-bitstream CLI options for VCU118

doc/FPGAs.yml, doc/vendors/xilinx.rst
Should solve #293.
Let me know if this level of information is ok.
=> Add documentation for Xilinx SPIx8 mode

src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
Should I add a board/ flash file? it will take some time/testing.
=> Artix+ AU25P support for Opal Kelly Board

src/lattice.cpp, src/lattice.hpp, src/main.cpp
Upsteam-Status: Submitted [https://github.com/traucucayre/openFPGALoader]
- Submitted to upstream, waiting approval
=> pass along reset parameters to provide control to the caller

src/colognechip.cpp
Fixes #387
Thanks for the report @machdyne
=> gatemate: fix dirtJtag support

doc/FPGAs.yml, src/main.cpp, src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
Merge the work of @cfib  [XADC_3 branch](https://github.com/cfib/openFPGALoaderXADC/tree/2e74386dbc8626eb888ed45b8fb25faca074ef34).
Tested on Artix 7 and Kintex Ultrascale.
=> XADC and DNA for Xilinx FPGA

doc/boards.yml, src/board.hpp
Board is essentially 1-1 with pynq z2, but more expensive (for non academic).
=> Add pynq-z1 board

src/gowin.cpp, src/lattice.cpp, src/xilinx.cpp
I got openFPGALoader to work with WebUSB with this patch (tested on OrangeCrab r0.2).
=> Add WebAssembly support

src/spiFlashdb.hpp
This should fix the "Unknown ID" issue
=> Added Zetta ZD25WQ16CSIGT

src/xilinx.cpp
This adds support to read the min/max temp, as well as the current+min/max VCCINT and VCCAUX registers (VCCBRAM could be added, but is normally the same as VCCINT).
This can be helpful for troubleshooting devices. I did change the JSON output format slightly to make it more "human friendly" by adding line breaks. However someone parsing the output *should* still be able to use their previous code, provided it can deal with reading in line ends.
```
{"temp": 39.9061, 
"maxtemp": 40.3194, 
"mintemp": 25.9852, 
"raw":  {"0": 40684, "1": 21949, "2": 39270, "3": 0, "4": 0, "5": 0, "6": 21948, "7": 0},
"vccint": 1.00415, 
"maxvccint": 1.00635, 
"minvccint": 1.00195, 
"vccaux": 1.79663, 
"maxvccaux": 1.79883, 
"minvccaux": 1.79517, 
}
```
The current/min/max could be made a dict for each …
=> xilinx: Add XADC reads of VCC registers

src/part.hpp
Hi i add a new device
Intel MAX10M40SCE144C8G -> https://www.mouser.de/ProductDetail/Altera/10M40SCE144C8G?qs=G%2FX6g08h60vA9eRBtuD3gQ%3D%3D
i tested the device, it works
=> add new device (Intel MAX10M40SCE144C8G)

README.md, src/main.cpp
This makes #438 better accessible for the casual user.
=> main: In help output, show how to detect flash

99-openfpgaloader.rules, doc/boards.yml, doc/cable.yml, src/board.hpp, src/cable.hpp
This pull request add support for the Numato Systems Mimas A7.
=> Add support for Numato Systems Mimas A7 board.

doc/FPGAs.yml, doc/boards.yml, src/board.hpp, src/part.hpp, src/xilinx.cpp, src/xilinx.hpp
Tested by loading a design on the VCU108 board.
No flash support for the moment.
=> Add support for VCU108 board and Virtex UltraScale

doc/guide/troubleshooting.rst
=> Add entry about updating firmware TangNano20K

doc/FPGAs.yml, src/part.hpp
Hi, this added support for loading bitstream into xc7k480t SRAM.
=> Add support for xc7k480t
